databases:
  - name: mltqa
    plan: free
    databaseName: mltqa
    user: mltqa

services:
  - type: web
    plan: free
    name: mltqa
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn mltqa.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mltqa
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4