# Generated by Django 4.2.23 on 2025-07-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='accept_status',
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(default='waiting', max_length=20),
        ),
    ]
