# Generated by Django 4.2.23 on 2025-07-27 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_request_accept_status_request_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='starts',
            new_name='stars',
        ),
    ]
