# Generated by Django 4.2.23 on 2025-07-27 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('home', '0006_rating_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='event',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='event_ratings', to='dashboard.event'),
            preserve_default=False,
        ),
    ]
